### ISSUE TITLE
Commander -v missing version number

### ISSUE THREAD

**Issue by modlin** [SimonBaeumer/commander#111]
### Prerequisites

* [x] Can you reproduce the problem?
* [x] Are you running the latest version?
* [x] Did you perform a cursory search?

### Description

The version option output does not contain version numbers.

### Steps to Reproduce

1. Install using go command according to https://github.com/SimonBaeumer/commander#installation :

        go get github.com/SimonBaeumer/commander/cmd/commander

2. On terminal, run:

        commander -v

**Expected behavior:**

Output:

    Commander version 0.3.0

**Actual behavior:**

Output:

    Commander version

### Specifications

 - Version: Commander 0.3.0 (As found in commit 3fa13b0, 2019-10)
 - Platform: Debian GNU/Linux 9.11 (stretch)
 - Subsystem: Perhaps go version? go1.7.4 linux/amd6

> You can get the version information from executing `commander --version`.

No. Whether `commander -v` or `commander --version`, version number is still missing.

**Comment by modlin** [comment]
Additional info:

Since my `commander -v` doesn't work, my expected output is based on looking at `$GOPATH/src/github.com/SimonBaeumer/commander/vendor/github.com/urfave/cli/help.go` :

```go
func printVersion(c *Context) {
	fmt.Fprintf(c.App.Writer, "%v version %v\n", c.App.Name, c.App.Version)
}
```

* Seems the output will be put together like this: `<app-name> version <version-number>`
* According to `CHANGELOG.md` the latest version number is `0.3.0`

So expected output would be something like:

    Commander version 0.3.0

I did a cursory search to see if the issue may have already been submitted. Seems from https://github.com/SimonBaeumer/commander/issues?utf8=%E2%9C%93&q=version , the most likely thread was:

    Fix version
    #15 by SimonBaeumer was merged on Mar 8, 2019
    1

https://github.com/SimonBaeumer/commander/pull/15 :

* From the minimal text I couldn't understand if it relates to missing version numbers or not.
* Files accompany this, so I look at the files.

https://github.com/SimonBaeumer/commander/pull/15/files

My go knowledge is limited but the most likely code relating to version output seemed to be in `cmd/commander/commander.go`:

* Has `var version string` to declare `version`
* But seems there are no assignments for variable `version`
* Also, `0.3.0` number not found

It is possible this code has been improved since this pull was written. The `go get ...` command had put a copy of the latest code to my computer, so I check my computer's copy.

In my `$GOPATH/src/github.com/SimonBaeumer/commander/cmd/commander/commander.go`, different lines, but same situation:

Line 14 defines a string variable `version`:

```go
var version string
```

Line 36 refers to it.

```go
cliapp.Version = version
```

But, again, `commander.go`:

* Has `var version string` to declare `version`
* But seems there are no assignments for variable `version`
* Also, `0.3.0` number not found

So how does commander know what version number it is, or how is version number set, in order for the output to include version number?

**Comment by SimonBaeumer** [comment]
Hey @modlin,
thanks for submitting this issue :)

First, it is correct that commander does not display a version number since you installed it viá `go get`. 
`go get` fetches the source from git which does not store any information about the current version inside the source code.

If you would download a release from the [releases github page](https://github.com/SimonBaeumer/commander/releases) the `commander -v` should work as expected because the `version` variable were set during compilation viá `ldflags`.

If you take a look in the `Makefile` you can see that the `release-*` targets pass `ldflags` to the go compiler.
```go
release-amd64:
	$(info INFO: Starting build $@)
	CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=$(TRAVIS_TAG) -s -w" -o release/$(cmd)-linux-amd64 $(exe)
```
In this case the `-X main.version=$(TRAVIS_TAG)` will read the environment variable `$TRAVIS_TAG`, which is set if a travis build is running on a newly created tag (i.e. for a release).

I hope this helps you with your question :)

**Comment by modlin** [comment]
Thanks for the release build details, makes more sense now :)

Indeed downloading `commander-linux-amd64`, enabling permissions, run with `-v`, successfully shows version number part:

    Commander version v1.3.0

Excerpt for `-v` without version number, my copy of commander that I got from go get is working fine, so I'll keep using it.

I just learned of commander via https://www.reddit.com/r/bash/comments/erdsr2/test_your_bash_scripts_easy_with_simple/  and it already saved me time writing tests and testing program outputs, so thanks for sharing this productivity tool!

**Comment by SimonBaeumer** [comment]
You're welcome! 
It makes me happy that you like to use it! :)
