### ISSUE TITLE
Add more features to docker

### ISSUE THREAD

**Issue by SimonBaeumer** [SimonBaeumer/commander#115]
- authenticate to private registries
- pull an image on time
- use a running image
- add privileged support

**Comment by dylanhitt1** [comment]
Would you mind elaborating on "pull an image on time"? I was thinking about modifying my fork to support auth for one of my use cases, so I've naturally become interested in this issue.

**Comment by SimonBaeumer** [comment]
Hey @dylanhitt1,
thanks for your input. I will take a look at this on tuesday and maybe implement it directly. 
I want to add a little bit documentation, see #116, on how new fields can be added to the `YAML` config. At the moment it is a little bit tricky because the configuration must be converted several times.

**Comment by dylanhitt1** [comment]
@SimonBaeumer thanks for your response. I'll be sure to follow #116. If you end up doing it directly that's awesome thank you. If not I'd be happy to open a pull request following the output of #116.

**Comment by SimonBaeumer** [comment]
@dylanhitt1 I managed to write the docs today :+1: 

I would love to get feedback on the tutorial. You can find more information about it in the pull request description.
https://github.com/SimonBaeumer/commander/pull/117

**Comment by dylanhitt1** [comment]
@SimonBaeumer Awesome!

I'll be sure to look at it either Monday or Tuesday. Thank you for the quick turnaround 😄

**Comment by SimonBaeumer** [comment]
@dylanhitt 
I implemented a first approach for authenticating to a registry, maybe you have more ideas on this ;)
Additionally I added env support for node configurations :)
