### ISSUE TITLE
Option to not discard environment of current shell?

### ISSUE THREAD

**Issue by fbartels** [SimonBaeumer/commander#80]
### Prerequisites

* [ ] Can you reproduce the problem in safe mode?
  * I could not find any indication how to enable safe mode in this repository (only mentioned in the issue template)
* [x] Are you running the latest version?
```
$ commander -v
Commander version v1.1.0
```
* [x] Are you reporting to the correct repository?
* [x] Did you perform a cursory search?

### Description

When running programs that are configurable through environment variables (for example inside of a container) running them through commander fails, since previously set variables are not present.

### Steps to Reproduce

1. run
```
$ commander add --stdout --no-file env
tests:
  env:
    exit-code: 0
    stdout: PWD=/home/user/current-dir

```
2. run `env` directly in the shell
3. notice that none of the env vars (except for PWD) are listed by `commander`

**Expected behavior:** commander has access to the environment of the shell it is executed in.

**Actual behavior:** no environment is preserved.

### Specifications

 - Version: v1.1.0
 - Platform: Ubuntu 16.04 as host, Debian 9 in container
 - Subsystem: 
 
You can get the version information from executing `commander --version`.

**Comment by fbartels** [comment]
Thought about this a bit more and the above behaviour has its upsides (tests are always reproducible) and downsides (all required and expected env variables need to go into commander.yaml).  

So maybe a better approach would be to record the current environment when doing `commander add`?

**Comment by SimonBaeumer** [comment]
Hey @fbartels,
thanks for your contribution!

As you correctly pointed out, reproducibility and simplicity were the reason why commander does not inherit the env variables from the parent shell. 

Further it is a little bit problematic to add env variables with the add command. For me a solution would be to add a flag like `--include-env-vars` for a generated test.
Further it still would be cool to use env variables, but I want them to be visible in the `yaml` test suite. An idea is to write the env variables and read them from the shell.

For example:
```yaml
tests:
  env: 
    PATH: ${PATH} #Read from current shell
```

**Comment by fbartels** [comment]
I like the idea to dynamically specify them in the yaml file, as this allows for randomly generated variable values to be picked up (but on the other hand I could also fix my test cases to use a static value there).

**Comment by SimonBaeumer** [comment]
I created a first pull request for the reading of env variables. ATM only the windows build fails.
https://github.com/SimonBaeumer/commander/pull/82

I did not implement an `--include-env-vars` option for the `add` command because it would be a huge mess of env variables added to the suite.

**Comment by fbartels** [comment]
Hi @SimonBaeumer,

thanks for your pr. I did a local build of commander and can confirm that for the basic test cases I did seems to work as intended (see above linked commit for the cases).

I did stumble upon the question how to properly quote my env values, but managed to find the proper way as this not makes my basic tests go green.
