### ISSUE TITLE
Need help getting windows server 2019 working

### ISSUE THREAD

**Issue by mcred** [SimonBaeumer/commander#99]
### Prerequisites

* [X] Can you reproduce the problem?
* [X] Are you running the latest version?
* [X] Did you perform a cursory search?

### Description

Following the instructions in the README to setup a testing environment with github actions and running `commander` does not have any output. I've tried a few variations of invoking commander, but all with the same results. The file will download, I can see it with `ls`, but running `/commander --version` has no output. I have tried adding it to the path (can confirm it's in the path), but running `commander --version` has the same results. 

### Steps to Reproduce

Add a github action with the following config: 
https://github.com/mcred/titan/blob/feature/e2e/.github/workflows/test.yml

Inspect output:
https://github.com/mcred/titan/commit/ee26a202ea5218314315bbb387705e97161abc17/checks?check_suite_id=268546125

**Expected behavior:**
`Commander version v1.2.1`

**Actual behavior:** [What actually happened]
No output, failure or exceptions. 

### Specifications

 - Version: v1.2.1 commander-windows-amd64
 - Platform: Windows Server 2019

**Comment by SimonBaeumer** [comment]
Hey @mcred,
I think the problem is that the binary is not suffixed with `.exe` on windows. 
On my machine with Windows 10 I couldn't get it working without the suffix.
Could check it if this would fix your problem?

**Comment by SimonBaeumer** [comment]
@mcred I added the suffix to the new deployment. If it does not work I will investigate more on this issue

**Comment by mcred** [comment]
That was the issue! I appreciate the quick feedback. Thanks for putting in all the work for this test runner. It was just what I was looking for.
